GLOBAL.setfenv(1, GLOBAL)

return {
    RECIPE_DESC = {
        --[[
        FIRENETTLES_A = "If you can't stand the heat, stay out of the garden.",
        KYNO_ICENETTLES_A = "The Garden is giving us a cold reception.",
        KYNO_TWIGGYNUTS_A = "A bunch of nuts.",
        DRUMSTICK_A = "Ready for gobbling.",
        SUCCULENT_PICKED_A = "I could eat that, but I'd rather not.",
        KYNO_WORM_BONE_A = "Ha ha worm, I have your bone.",
        KYNO_SHARK_FIN_A = "A sleek fin.",
        OCEANFISH_MIDNIGHT_CARP_INV_A = "A moonlit swimmer from shadowed waters.",
        KYNO_MOON_FROGLEGS_A = "Frog legs infused with the Moon power.",
        KYNO_SALMONFISH_A = "Mm, fresh fish.",
        KYNO_SAP_A = "It tastes sweet.",
        FOLIAGE_A = "Some leafy greens.",
        BUTTER_A = "I can't believe it's butter!",
        KYNO_POISON_FROGLEGS_A = "Looks noxious.",
        KYNO_CRABMEAT_A = "No imitations here.",
        GOATMILK_A = "It's buzzing with tastiness!",
        KYNO_PIKO_A = "He's a bit of a nut job.",
        KYNO_PIKO_ORANGE_A = "For some reason I'm craving tea.",
        KYNO_BEANBUGS_A = "Beans. With legs.",
        KYNO_LIMPETS_A = "Maybe starving wouldn't be so bad.",
        MANDRAKE_A = "Mandrake roots have strange properties.",
        KYNO_CRABKINGMEAT_A = "No imitations here.",
        KYNO_SWORDFISH_DEAD_A = "I better not touch this.",
        KYNO_SWORDFISH_BLUE_A = "A swordfish that forgot how to sword... or swim.",
        WOBSTER_MONKEYISLAND_LAND_A = "What a fancy lobster! Looks expensive.",

        -- New items (README.md line 32-63)
        KYNO_CAVETUBER_BLOOMING_A = "It's a blooming tuber!",
        KYNO_TAROROOT_A = "Looks like a purple pepper.",
        KYNO_LOTUS_FLOWER_A = "A lovely science flower.",
        KYNO_WATERYCRESS_A = "That's new.",
        KYNO_CHICKEN2_A = "A bird used for poultry.",
        KYNO_CHICKEN_EGG_A = "A small, chicken egg.",
        KYNO_TEALEAF_A = "Tea leaf.",
        KYNO_BRAINROCK_CORAL_A = "Food for thought.",
        KYNO_MUSSEL_A = "Could use some flexing.",
        KYNO_FENNEL_A = "It's like a carrot, but green.",
        ICE_A = "Ice to meet you.",
        HONEY_A = "Looks delicious!",
        BERRIES_A = "Red berries taste the best.",
        BUTTERFLY_A = "Butterfly, flutter by.",
        PONDEEL_A = "This will make a delicious meal.",
        KYNO_GROUPER_A = "Surf and turf, hold the turf.",
        ROYAL_JELLY_A = "It infuses the eater with the power of science!",
        LAVAE_EGG_A = "There's a faint warmth coming from inside.",
        BEARGER_FUR_A = "A mat of thick fur.",
        DEERCLOPS_EYEBALL_A = "This is really gross.",
        KYNO_KOKONUT_A = "It requires a large nut hacker.",
        KYNO_PINEAPPLE_A = "It requires a crack.",
        KYNO_HUMANMEAT_A = "Flesh is flesh. Where do I draw the line?",
        KYNO_JELLYFISH_DEAD_A = "It lived a good life. Maybe",
        KYNO_JELLYFISH_RAINBOW_A = "A colorful blob of science.",
        ANCIENTFRUIT_NIGHTVISION_A = "I just wish it was less... twitchy.",
        KYNO_SYRUP_A = "Adds sweetness to the mixture.",
        KYNO_SUGARFLY_A = "Sugarfly, flutter by.",
        MOONBUTTERFLY_A = "My vast scientific knowledge tells me it's... a moon butterfly.",
        FIG_A = "I'll call it \"Newton's Fig\".",
        CHOCOLATE_BLACK_A = "Chocolate",
        CHOCOLATE_WHITE_A = "White Chocolate",
        ]]
    },
}
