GLOBAL.setfenv(1, GLOBAL)

return {
    RECIPE_DESC = {
        FIRENETTLES_A = "If you can't stand the heat, stay out of the garden.",
        KYNO_ICENETTLES_A = "The Garden is giving us a cold reception.",
        KYNO_TWIGGYNUTS_A = "A bunch of nuts.",
        DRUMSTICK_A = "Ready for gobbling.",
        SUCCULENT_PICKED_A = "I could eat that, but I'd rather not.",
        KYNO_WORM_BONE_A = "Ha ha worm, I have your bone.",
        KYNO_SHARK_FIN_A = "A sleek fin.",
        OCEANFISH_MIDNIGHT_CARP_INV_A = "A moonlit swimmer from shadowed waters.",
        KYNO_MOON_FROGLEGS_A = "Frog legs infused with the Moon power.",
        KYNO_SALMONFISH_A = "Mm, fresh fish.",
        KYNO_SAP_A = "It tastes sweet.",
        FOLIAGE_A = "Some leafy greens.",
        BUTTER_A = "I can't believe it's butter!",
        KYNO_POISON_FROGLEGS_A = "Looks noxious.",
        KYNO_CRABMEAT_A = "No imitations here.",
        GOATMILK_A = "It's buzzing with tastiness!",
        KYNO_PIKO_A = "He's a bit of a nut job.",
        KYNO_PIKO_ORANGE_A = "For some reason I'm craving tea.",
        KYNO_BEANBUGS_A = "Beans. With legs.",
        KYNO_LIMPETS_A = "Maybe starving wouldn't be so bad.",
        MANDRAKE_A = "Mandrake roots have strange properties.",
        KYNO_CRABKINGMEAT_A = "No imitations here.",
        KYNO_SWORDFISH_DEAD_A = "I better not touch this.",
        KYNO_SWORDFISH_BLUE_A = "A swordfish that forgot how to sword... or swim.",
        WOBSTER_MONKEYISLAND_LAND_A = "What a fancy lobster! Looks expensive.",
    },
}
