--[[
If you want to modify the item quantity or price, you can edit this file.
min is the minimum amount replenished daily, and max is the maximum amount replenished daily.
limit is the upper cap on the item quantity. If you fill in a value for limit, any unsold items from the day will carry over to the next day.

For example:
firenettles = {ingredients = {kyno_pigcoin1 = 2}, min = 10, max = 20, limit = 30}
Each day, the stock will increase by 10–20 items on top of the existing inventory, until the total reaches 30.

However, if you omit limit – for example:
firenettles = {ingredients = {kyno_pigcoin1 = 2}, min = 10, max = 20}
– the daily stock will be reset to a random number between 10 and 20 each day, without any accumulation.
]]

local REBALANCE_RECIPES = {

    firenettles                  = {ingredients = {kyno_pigcoin1 = 2}},
    kyno_icenettles              = {ingredients = {kyno_pigcoin1 = 2}},
    kyno_twiggynuts              = {ingredients = {kyno_pigcoin1 = 2}},
    drumstick                    = {ingredients = {kyno_pigcoin1 = 2}},
    succulent_picked             = {ingredients = {kyno_pigcoin1 = 1}},
    kyno_worm_bone               = {ingredients = {kyno_pigcoin2 = 1}},
    kyno_shark_fin               = {ingredients = {kyno_pigcoin2 = 1}},
    oceanfish_midnight_carp_inv  = {ingredients = {kyno_pigcoin2 = 1}},
    kyno_moon_froglegs           = {ingredients = {kyno_pigcoin2 = 1}},
    kyno_salmonfish              = {ingredients = {kyno_pigcoin2 = 1}},
    kyno_sap                     = {ingredients = {kyno_pigcoin1 = 1}},
    foliage                      = {ingredients = {kyno_pigcoin1 = 1}},
    butter                       = {ingredients = {kyno_pigcoin1 = 5}},
    kyno_poison_froglegs         = {ingredients = {kyno_pigcoin2 = 1}},
    kyno_crabmeat                = {ingredients = {kyno_pigcoin2 = 1}},
    goatmilk                     = {ingredients = {kyno_pigcoin1 = 2}},
    kyno_piko                    = {ingredients = {kyno_pigcoin2 = 1}},
    kyno_piko_orange             = {ingredients = {kyno_pigcoin2 = 1}},
    kyno_beanbugs                = {ingredients = {kyno_pigcoin2 = 1                   }, numtogive = 2},
    kyno_limpets                 = {ingredients = {kyno_pigcoin2 = 1}},
    mandrake                     = {ingredients = {kyno_pigcoin3 = 1, kyno_pigcoin2 = 5}},
    kyno_crabkingmeat            = {ingredients = {kyno_pigcoin3 = 1, kyno_pigcoin2 = 5}},
    kyno_swordfish_dead          = {ingredients = {kyno_pigcoin3 = 1, kyno_pigcoin2 = 5}},
    kyno_swordfish_blue          = {ingredients = {kyno_pigcoin3 = 1, kyno_pigcoin2 = 5}},

    kyno_cavetuber_blooming      = {ingredients = {kyno_pigcoin1 = 2}},
    kyno_taroroot                = {ingredients = {kyno_pigcoin1 = 2}},
    kyno_lotus_flower            = {ingredients = {kyno_pigcoin1 = 2}},
    kyno_waterycress             = {ingredients = {kyno_pigcoin1 = 2}},
    kyno_chicken2                = {ingredients = {kyno_pigcoin2 = 1}},
    kyno_chicken_egg             = {ingredients = {kyno_pigcoin1 = 2}},
    kyno_tealeaf                 = {ingredients = {kyno_pigcoin1 = 1}},
    kyno_brainrock_coral         = {ingredients = {kyno_pigcoin3 = 1, kyno_pigcoin2 = 5}},
    kyno_mussel                  = {ingredients = {kyno_pigcoin1 = 1}},
    kyno_fennel                  = {ingredients = {kyno_pigcoin1 = 2}},
    ice                          = {ingredients = {kyno_pigcoin1 = 1}},
    honey                        = {ingredients = {kyno_pigcoin1 = 1}},
    berries                      = {ingredients = {kyno_pigcoin1 = 1}},
    butterfly                    = {ingredients = {kyno_pigcoin1 = 1}},
    pondeel                      = {ingredients = {kyno_pigcoin2 = 1                   }, numtogive = 2},
    kyno_grouper                 = {ingredients = {kyno_pigcoin1 = 2}},
    royal_jelly                  = {ingredients = {kyno_pigcoin3 = 1, kyno_pigcoin2 = 5}},
    lavae_egg                    = {ingredients = {kyno_pigcoin3 = 1, kyno_pigcoin2 = 5}},
    bearger_fur                  = {ingredients = {kyno_pigcoin3 = 1, kyno_pigcoin2 = 5}},
    deerclops_eyeball            = {ingredients = {kyno_pigcoin3 = 1, kyno_pigcoin2 = 5}},
    kyno_pineapple               = {ingredients = {kyno_pigcoin2 = 1                   }, numtogive = 2},
    kyno_humanmeat               = {ingredients = {kyno_pigcoin1 = 1}},
    kyno_jellyfish_dead          = {ingredients = {kyno_pigcoin1 = 1}},
    kyno_jellyfish_rainbow       = {ingredients = {kyno_pigcoin2 = 1                   }, numtogive = 2},
    kyno_syrup                   = {ingredients = {kyno_pigcoin1 = 2}},
    kyno_sugarfly                = {ingredients = {kyno_pigcoin2 = 1                   }, numtogive = 3},
    moonbutterfly                = {ingredients = {kyno_pigcoin2 = 1                   }, numtogive = 3},
    fig                          = {ingredients = {kyno_pigcoin1 = 2}},
    chocolate_black              = {ingredients = {kyno_pigcoin1 = 2}},
    chocolate_white              = {ingredients = {kyno_pigcoin1 = 3}},

    wobster_monkeyisland_land    = {ingredients = {kyno_pigcoin3 = 1, kyno_pigcoin2 = 5}},
    kyno_banana                  = {ingredients = {kyno_pigcoin1 = 1}},
    kyno_kokonut                 = {ingredients = {kyno_pigcoin1 = 1}},
    kyno_coffeebeans             = {ingredients = {kyno_pigcoin1 = 1}},
    wormlight                    = {ingredients = {kyno_pigcoin1 = 1}},
    ancientfruit_nightvision     = {ingredients = {kyno_pigcoin2 = 1                   }, numtogive = 2},
    kyno_spotspice_leaf          = {ingredients = {kyno_pigcoin1 = 1}},
    kyno_wheat                   = {ingredients = {kyno_pigcoin1 = 1}},
    kyno_milk_beefalo            = {ingredients = {kyno_pigcoin1 = 1}},
    kyno_milk_koalefant          = {ingredients = {kyno_pigcoin1 = 1}},
    cheese_yellow                = {ingredients = {kyno_pigcoin1 = 2}},
    cheese_white                 = {ingredients = {kyno_pigcoin1 = 2}},
    cheese_koalefant             = {ingredients = {kyno_pigcoin1 = 2}},
    cutlichen                    = {ingredients = {kyno_pigcoin1 = 1}},
    smallmeat                    = {ingredients = {kyno_pigcoin1 = 1}},
    meat                         = {ingredients = {kyno_pigcoin1 = 1}},
    monstermeat                  = {ingredients = {kyno_pigcoin1 = 1}},
    plantmeat                    = {ingredients = {kyno_pigcoin1 = 1}},
    froglegs                     = {ingredients = {kyno_pigcoin1 = 1}},
    trunk_summer                 = {ingredients = {kyno_pigcoin1 = 2}},
    trunk_winter                 = {ingredients = {kyno_pigcoin1 = 2}},
    bird_egg                     = {ingredients = {kyno_pigcoin1 = 1}},
    oceanfish_small_8_inv        = {ingredients = {kyno_pigcoin3 = 1, kyno_pigcoin2 = 5}},
    oceanfish_medium_8_inv       = {ingredients = {kyno_pigcoin3 = 1, kyno_pigcoin2 = 5}},
    kyno_oil                     = {ingredients = {kyno_pigcoin1 = 2}},
    kyno_aloe                    = {ingredients = {kyno_pigcoin1 = 1}},
    kyno_radish                  = {ingredients = {kyno_pigcoin1 = 1}},
    kyno_rice                    = {ingredients = {kyno_pigcoin1 = 1}},
    kyno_sweetpotato             = {ingredients = {kyno_pigcoin1 = 1}},
    kyno_turnip                  = {ingredients = {kyno_pigcoin1 = 1}},
    kyno_parznip                 = {ingredients = {kyno_pigcoin1 = 1}},
    kyno_cucumber                = {ingredients = {kyno_pigcoin1 = 1}},
    littlebread                  = {ingredients = {kyno_pigcoin1 = 2}},
    berries_juicy                = {ingredients = {kyno_pigcoin1 = 1}},
    gorge_bread                  = {ingredients = {kyno_pigcoin1 = 2}},

    kyno_opalpreciouspowder      = {ingredients = {kyno_pigcoin3 = 1}},
    kyno_blubber                 = {ingredients = {kyno_pigcoin2 = 1}},
    kyno_salt                    = {ingredients = {kyno_pigcoin1 = 1}},
    kyno_gummybug                = {ingredients = {kyno_pigcoin2 = 1}},
    kyno_seaweeds                = {ingredients = {kyno_pigcoin1 = 1}},
    oceanfish_medium_4_inv       = {ingredients = {kyno_pigcoin2 = 1}},
    milkywhites                  = {ingredients = {kyno_pigcoin2 = 1}},
}

return REBALANCE_RECIPES